# netlify.toml

[build]
  command = "jekyll build --source docs"
  publish = "_site"

# By setting this in the production context, we strongly hint to Netlify
# that this is a Ruby-based build, not a Python one.
[context.production.environment]
  RUBY_VERSION = "3.1.2"