# netlify.toml

[build]
  # This single command tells Netlify to first install the Ruby gems
  # from the Gemfile, and THEN build the Jekyll site.
  # This overrides the default behavior of trying to install Python packages.
  command = "bundle install && bundle exec jekyll build --source docs"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.2"